/*
Copyright (C) 2023-2026 Chaos
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License.
*/

export type CatalogCategory =
  | "primitives"
  | "forms"
  | "navigation"
  | "feedback"
  | "overlay"
  | "data"
  | "layout"
  | "business";

export type CatalogItem = {
  id: string;
  tag: string;
  name: string;
  category: CatalogCategory;
  description: string;
  status: "stable" | "beta";
  props: string[];
  events?: string[];
};

const item = (
  id: string,
  tag: string,
  name: string,
  category: CatalogCategory,
  description: string,
  props: string[],
  events: string[] = [],
  status: "stable" | "beta" = "stable",
): CatalogItem => ({ id, tag, name, category, description, props, events, status });

export const catalog: CatalogItem[] = [
  item(
    "button",
    "aui-button",
    "Button",
    "primitives",
    "Primary, secondary and destructive actions with loading and disabled states.",
    ["variant", "size", "loading", "disabled"],
  ),
  item(
    "card",
    "aui-card",
    "Card",
    "layout",
    "Sharp surface container with header, content and footer slots.",
    ["header", "footer"],
  ),
  item(
    "icon-button",
    "aui-icon-button",
    "Icon Button",
    "primitives",
    "Compact row actions with an accessible label and danger treatment.",
    ["label", "icon", "variant", "size"],
  ),
  item(
    "badge",
    "aui-badge",
    "Badge",
    "primitives",
    "Compact semantic labels for categories, counters and operational state.",
    ["variant", "dot"],
  ),
  item(
    "status-tag",
    "aui-status-tag",
    "Status Tag",
    "primitives",
    "Monospace status indicator for success, error, warning and neutral state.",
    ["status"],
  ),
  item(
    "avatar",
    "aui-avatar",
    "Avatar",
    "primitives",
    "Square identity mark with image, initials and three density sizes.",
    ["src", "alt", "initials", "size"],
  ),
  item(
    "progress",
    "aui-progress",
    "Progress",
    "primitives",
    "Determinate progress bar with an accessible value range.",
    ["value", "max", "label", "show-value"],
  ),
  item(
    "rating",
    "aui-rating",
    "Rating",
    "primitives",
    "Keyboard-friendly star rating with read-only mode.",
    ["value", "max", "readonly"],
    ["aui-rating-change"],
  ),
  item(
    "kbd",
    "aui-kbd",
    "Keyboard Key",
    "primitives",
    "Terminal-style keyboard shortcut hint.",
    [],
  ),
  item(
    "color-tag",
    "aui-color-tag",
    "Color Tag",
    "primitives",
    "Small color swatch paired with a semantic label.",
    ["color", "label"],
  ),
  item(
    "number-input",
    "aui-number-input",
    "Number Input",
    "forms",
    "Bounded numeric input with increment and decrement controls.",
    ["value", "min", "max", "step"],
    ["aui-number-change"],
  ),
  item(
    "input",
    "aui-input",
    "Input",
    "forms",
    "Single-line text input with invalid and disabled states.",
    ["value", "type", "name", "placeholder", "invalid"],
    ["aui-input", "aui-change"],
  ),
  item(
    "textarea",
    "aui-textarea",
    "Textarea",
    "forms",
    "Resizable multiline text input for notes, descriptions and payloads.",
    ["value", "rows", "placeholder", "invalid"],
    ["aui-input"],
  ),
  item(
    "select",
    "aui-select",
    "Select",
    "forms",
    "Native select surface with object options through a DOM property.",
    ["value", "options", "disabled", "invalid"],
    ["aui-change"],
  ),
  item(
    "combobox",
    "aui-combobox",
    "Combobox",
    "forms",
    "Searchable single selection with keyboard navigation and option descriptions.",
    ["options", "value", "placeholder", "open"],
    ["aui-change"],
  ),
  item(
    "multi-select",
    "aui-multi-select",
    "Multi Select",
    "forms",
    "Chip-based multiple selection for filters and permissions.",
    ["options", "values", "placeholder"],
    ["aui-change"],
  ),
  item(
    "password-input",
    "aui-password-input",
    "Password Input",
    "forms",
    "Password field with explicit reveal and hide action.",
    ["value", "placeholder", "reveal-label"],
    ["aui-input"],
  ),
  item(
    "checkbox",
    "aui-checkbox",
    "Checkbox",
    "forms",
    "Native checkbox with a visible label and checked event.",
    ["checked", "disabled", "label"],
    ["aui-checked-change"],
  ),
  item(
    "switch",
    "aui-switch",
    "Switch",
    "forms",
    "Binary setting control for enablement and feature flags.",
    ["checked", "disabled", "label"],
    ["aui-checked-change"],
  ),
  item(
    "radio-group",
    "aui-radio-group",
    "Radio Group",
    "forms",
    "Single-choice group with horizontal and vertical orientations.",
    ["options", "value", "orientation"],
    ["aui-radio-change"],
  ),
  item(
    "slider",
    "aui-slider",
    "Slider",
    "forms",
    "Range control for bounded numeric configuration.",
    ["value", "min", "max", "step"],
    ["aui-slider-change"],
  ),
  item(
    "tag-input",
    "aui-tag-input",
    "Tag Input",
    "forms",
    "Token entry with Enter/comma creation and removal actions.",
    ["values", "placeholder"],
    ["aui-tags-change"],
  ),
  item(
    "input-group",
    "aui-input-group",
    "Input Group",
    "forms",
    "Prefix and suffix composition around a native input.",
    [],
    [],
  ),
  item(
    "field",
    "aui-field",
    "Field",
    "forms",
    "Label, description, required marker and error message composition.",
    ["label", "description", "error", "required"],
  ),
  item(
    "file-upload",
    "aui-file-upload",
    "File Upload",
    "forms",
    "Accessible browse and drag-and-drop file input.",
    ["accept", "multiple", "label", "hint"],
    ["aui-files-change"],
  ),
  item(
    "search",
    "aui-search",
    "Search",
    "forms",
    "Debounced search field with clear action.",
    ["value", "placeholder", "debounce"],
    ["aui-search"],
  ),
  item(
    "toggle",
    "aui-toggle",
    "Toggle",
    "navigation",
    "Pressed/unpressed action state.",
    ["pressed", "label"],
    ["aui-toggle-change"],
  ),
  item(
    "toggle-group",
    "aui-toggle-group",
    "Toggle Group",
    "navigation",
    "Segmented single selection group.",
    ["items", "value"],
    ["aui-toggle-group-change"],
  ),
  item(
    "segmented",
    "aui-segmented",
    "Segmented Control",
    "navigation",
    "Compact view or filter mode switcher.",
    ["items", "value"],
    ["aui-segment-change"],
  ),
  item(
    "tabs",
    "aui-tabs",
    "Tabs",
    "navigation",
    "ARIA tablist with explicit active state.",
    ["items", "active"],
    ["aui-tab-change"],
  ),
  item(
    "breadcrumb",
    "aui-breadcrumb",
    "Breadcrumb",
    "navigation",
    "PATH-oriented location trail for nested systems.",
    ["items"],
  ),
  item(
    "nav",
    "aui-nav",
    "Navigation",
    "navigation",
    "Primary navigation with active and disabled semantics.",
    ["items"],
    ["aui-nav-change"],
  ),
  item(
    "pagination",
    "aui-pagination",
    "Pagination",
    "navigation",
    "Server-side pagination summary with previous and next controls.",
    ["page", "total-pages", "total", "page-size"],
    ["aui-page-change"],
  ),
  item(
    "accordion",
    "aui-accordion",
    "Accordion",
    "navigation",
    "Disclosure collection for dense configuration screens.",
    ["items", "multiple"],
  ),
  item(
    "collapsible",
    "aui-collapsible",
    "Collapsible",
    "navigation",
    "Single disclosure block with open change event.",
    ["open", "title"],
    ["aui-open-change"],
  ),
  item(
    "stepper",
    "aui-stepper",
    "Stepper",
    "navigation",
    "Progressive workflow indicator for multi-step operations.",
    ["items", "active", "orientation"],
  ),
  item(
    "list",
    "aui-list",
    "List",
    "navigation",
    "Selectable or informational vertical list.",
    ["items", "selected", "selectable"],
    ["aui-list-change"],
  ),
  item(
    "tree",
    "aui-tree",
    "Tree",
    "navigation",
    "Expandable hierarchical navigation with selection.",
    ["nodes", "selected", "expanded"],
    ["aui-tree-change"],
  ),
  item(
    "timeline",
    "aui-timeline",
    "Timeline",
    "navigation",
    "Chronological event stream for audit and workflow history.",
    ["items"],
  ),
  item(
    "alert",
    "aui-alert",
    "Alert",
    "feedback",
    "Inline system message with semantic severity and optional close action.",
    ["variant", "title", "description", "closable"],
    ["aui-close"],
  ),
  item(
    "result",
    "aui-result",
    "Result",
    "feedback",
    "Success, warning, error or informational completion state.",
    ["status", "title", "description"],
  ),
  item(
    "empty-state",
    "aui-empty-state",
    "Empty State",
    "feedback",
    "Explicit no-data state that does not look like an error.",
    ["title", "description"],
  ),
  item(
    "error-state",
    "aui-error-state",
    "Error State",
    "feedback",
    "Recoverable error region with alert semantics and retry slot.",
    ["title", "description"],
  ),
  item(
    "spinner",
    "aui-spinner",
    "Spinner",
    "feedback",
    "Compact progress indicator for inline asynchronous work.",
    [],
  ),
  item(
    "skeleton",
    "aui-skeleton",
    "Skeleton",
    "feedback",
    "Reduced-motion-aware loading placeholder.",
    ["width", "height"],
  ),
  item(
    "toast",
    "aui-toast",
    "Toast",
    "feedback",
    "Transient notification with severity, duration and close behavior.",
    ["open", "title", "message", "variant", "duration"],
    ["aui-close"],
  ),
  item(
    "copyable-text",
    "aui-copyable-text",
    "Copyable Text",
    "feedback",
    "Truncated mono text with an accessible copy action.",
    ["text", "copy-label"],
    ["aui-copy"],
  ),
  item(
    "separator",
    "aui-separator",
    "Separator",
    "feedback",
    "Horizontal or vertical structural divider.",
    ["vertical"],
  ),
  item(
    "tooltip",
    "aui-tooltip",
    "Tooltip",
    "overlay",
    "Lightweight contextual hint for controls and icon actions.",
    ["content", "side"],
  ),
  item(
    "popover",
    "aui-popover",
    "Popover",
    "overlay",
    "Anchored content panel for non-modal contextual interaction.",
    ["open", "title"],
    ["aui-open-change"],
  ),
  item(
    "dropdown",
    "aui-dropdown",
    "Dropdown Menu",
    "overlay",
    "Command menu with shortcuts, separators and danger actions.",
    ["items", "open"],
    ["aui-menu-select"],
  ),
  item(
    "command",
    "aui-command",
    "Command Palette",
    "overlay",
    "Keyboard-first searchable command surface.",
    ["items", "open", "placeholder"],
    ["aui-command"],
  ),
  item(
    "dialog",
    "aui-dialog",
    "Dialog",
    "overlay",
    "Native modal dialog with ESC and backdrop close behavior.",
    ["open", "title", "description", "close-label"],
    ["aui-close"],
  ),
  item(
    "confirm-dialog",
    "aui-confirm-dialog",
    "Confirm Dialog",
    "overlay",
    "Explicit confirmation surface for destructive and irreversible actions.",
    ["open", "title", "description", "danger", "loading"],
    ["aui-confirm", "aui-cancel"],
  ),
  item(
    "drawer",
    "aui-drawer",
    "Drawer",
    "overlay",
    "Full-height side panel for forms and detail views.",
    ["open", "title", "side", "width"],
    ["aui-close"],
  ),
  item(
    "data-list",
    "aui-data-list",
    "Data List",
    "data",
    "Label/value presentation for metadata and detail pages.",
    ["items"],
  ),
  item(
    "table",
    "aui-table",
    "Table",
    "data",
    "Scrollable table frame with stable loading and empty states.",
    ["loading", "empty", "loading-label", "empty-label"],
  ),
  item(
    "data-grid",
    "aui-data-grid",
    "Data Grid",
    "data",
    "Configurable column/row grid for framework-neutral tabular data.",
    ["columns", "rows", "loading", "empty-label"],
  ),
  item(
    "calendar",
    "aui-calendar",
    "Date Input",
    "data",
    "Native date input with min/max boundaries.",
    ["value", "min", "max", "label"],
    ["aui-date-change"],
  ),
  item(
    "calendar-grid",
    "aui-calendar-grid",
    "Calendar Grid",
    "data",
    "Interactive month calendar grid with navigation.",
    ["month", "year", "selected"],
    ["aui-date-change"],
  ),
  item(
    "date-range",
    "aui-date-range",
    "Date Range",
    "data",
    "Two-ended date filter for reporting and analytics.",
    ["start", "end", "start-label", "end-label"],
    ["aui-range-change"],
  ),
  item(
    "color-picker",
    "aui-color-picker",
    "Color Picker",
    "forms",
    "Native color selection with a semantic value event.",
    ["value", "label"],
    ["aui-color-change"],
  ),
  item(
    "chart-container",
    "aui-chart-container",
    "Chart Container",
    "data",
    "Theme-aware chart frame that accepts any renderer through a slot.",
    ["title", "description", "height"],
  ),
  item(
    "json-viewer",
    "aui-json-viewer",
    "JSON Viewer",
    "data",
    "Expandable structured payload viewer for API and debug screens.",
    ["value", "title", "expanded"],
  ),
  item(
    "log-viewer",
    "aui-log-viewer",
    "Log Viewer",
    "data",
    "Monospace live log stream with severity columns.",
    ["entries", "follow"],
  ),
  item(
    "kanban",
    "aui-kanban",
    "Kanban Board",
    "data",
    "Drag-and-drop work board for operational queues.",
    ["columns"],
    ["aui-kanban-change"],
  ),
  item(
    "container",
    "aui-container",
    "Container",
    "layout",
    "Centered or full-width content boundary.",
    ["max-width", "centered"],
  ),
  item(
    "stack",
    "aui-stack",
    "Stack",
    "layout",
    "Tokenized flex layout for vertical and horizontal composition.",
    ["direction", "gap", "align", "justify"],
  ),
  item(
    "grid",
    "aui-grid",
    "Grid",
    "layout",
    "Responsive equal-column layout with mobile collapse.",
    ["columns", "gap", "min-width"],
  ),
  item(
    "splitter",
    "aui-splitter",
    "Splitter",
    "layout",
    "Two-panel composition primitive for consoles and inspectors.",
    ["direction", "initial", "min"],
  ),
  item(
    "shell",
    "aui-shell",
    "Admin Shell",
    "layout",
    "Responsive application shell with sidebar, header and content slots.",
    ["sidebar-width", "header-height"],
  ),
  item(
    "page",
    "aui-page",
    "Admin Page",
    "layout",
    "Page-level heading and content rhythm for operational screens.",
    ["title", "description"],
  ),
  item(
    "page-header",
    "aui-page-header",
    "Page Header",
    "layout",
    "Reusable heading/action row outside the full page wrapper.",
    ["title", "description"],
  ),
  item(
    "filter-bar",
    "aui-filter-bar",
    "Filter Bar",
    "layout",
    "Wrapped filter surface for search, select and bulk controls.",
    [],
  ),
  item("stat", "aui-stat", "Stat", "layout", "Large tabular metric with unit and trend support.", [
    "label",
    "value",
    "unit",
    "trend",
  ]),
  item(
    "aspect-ratio",
    "aui-aspect-ratio",
    "Aspect Ratio",
    "layout",
    "Stable media or preview frame with a controlled ratio.",
    ["ratio"],
  ),
  item(
    "scroll-area",
    "aui-scroll-area",
    "Scroll Area",
    "layout",
    "Explicit bounded scrolling region for dense content.",
    ["orientation", "max-height"],
  ),
  item(
    "code-block",
    "aui-code-block",
    "Code Block",
    "data",
    "Copyable syntax-neutral code surface for docs and diagnostics.",
    ["code", "language"],
    ["aui-copy"],
  ),
];

catalog.push(
  item(
    "crud-page",
    "aui-crud-page",
    "CRUD Page",
    "business",
    "Page shell for list, filters, toolbar and pagination workflows.",
    ["title", "description", "loading"],
  ),
  item(
    "crud-toolbar",
    "aui-crud-toolbar",
    "CRUD Toolbar",
    "business",
    "Search, selected-row summary, refresh and bulk action composition.",
    ["selected", "search-placeholder", "loading"],
    ["aui-search", "aui-refresh"],
  ),
  item(
    "advanced-table",
    "aui-advanced-table",
    "Advanced Table",
    "business",
    "Selectable and sortable table for generic enterprise records.",
    ["columns", "rows", "selectable", "loading"],
    ["aui-selection-change", "aui-sort-change"],
  ),
  item(
    "form-builder",
    "aui-form-builder",
    "Form Builder",
    "business",
    "Schema-driven form renderer for common field types.",
    ["fields", "submit-label", "loading"],
    ["aui-form-change", "aui-form-submit"],
  ),
  item(
    "approval-timeline",
    "aui-approval-timeline",
    "Approval Timeline",
    "business",
    "Approval and review progress for enterprise workflows.",
    ["items", "active"],
  ),
  item(
    "metric-card",
    "aui-metric-card",
    "Metric Card",
    "business",
    "High-signal KPI block with unit, trend and tone.",
    ["label", "value", "unit", "trend", "tone"],
  ),
  item(
    "metric-grid",
    "aui-metric-grid",
    "Metric Grid",
    "business",
    "Responsive group of operational KPIs.",
    ["items", "columns"],
  ),
  item(
    "bar-chart",
    "aui-bar-chart",
    "Bar Chart",
    "business",
    "Small dependency-free bar chart for basic operational trends.",
    ["data", "height", "label"],
  ),
  item(
    "sparkline",
    "aui-sparkline",
    "Sparkline",
    "business",
    "Compact trend line for tables and metric cards.",
    ["values", "label", "color"],
  ),
);

export const categoryLabels: Record<CatalogCategory, string> = {
  primitives: "Primitives",
  forms: "Forms & Input",
  navigation: "Navigation",
  feedback: "Feedback",
  overlay: "Overlay",
  data: "Data Display",
  layout: "Layout",
  business: "Business Systems",
};

export const implementedTags = new Set(catalog.map((entry) => entry.tag));
